### PR TITLE
Moved mockup file to Resources folder

### PR DESCRIPTION
**Pull request by GKouhia**
Hi -- hope this works!
thanks for all!
G

### CODE REVIEW

**Comment by GKouhia** [comment]
Hi
Thank you Joan. I bet it's great. I'm hip deep in family stuff. I'll look tonight late or tomorrow. 
Again thanks.
Glenn

**Comment by GKouhia** [comment]
I assumed you sent the css for this week and I'm now thinking the link below was for the Friday updates I sent with a pull request. 
Let's talk tomorrow afternoon.
Thanks,
Glenn

**Comment by jel04h** [comment]
We've had it a bit rough this weekend--my mom went back to Florida, and we haven't slept. I know we are supposed to do shifts, but the baby has just been inconsolable at night for some reason even after every checkbox has been checked...we think he wants his grandma back. I'll have to get the project done Mon or Tues, sorry about this! I did work on the css a little, so I do have some progress. -Joan

**Comment by GKouhia** [comment]
No Worries, Joan.
I used to do 3 things to quiet our crying babies: hold them and rock or bounce gently, place my pinky or a binky in the baby's mouth to suck on (actually helps to clear their ears when they become congested and feel pressure in their ear canals) on, and make sure their bottoms and diapers were always dry. Those things will work much better than any semantic html or css ever will.
I’ll look at the assignment this afternoon and email back later today.
Thanks and good luck with your baby.
G

**Comment by jel04h** [comment]
Thanks for the tips! I'm pretty sure he has a cold...and he's not happy about it!

```
On Monday, December 7, 2015 9:15 AM, Glenn Kouhia <notifications@github.com> wrote:
```

 No Worries, Joan.
I used to do 3 things to quiet our crying babies: hold them and rock or bounce gently, place my pinky or a binky in the baby's mouth to suck on (actually helps to clear their ears when they become congested and feel pressure in their ear canals) on, and make sure their bottoms and diapers were always dry. Those things will work much better than any semantic html or css ever will.
I’ll look at the assignment this afternoon and email back later today.
Thanks and good luck with your baby.
G

**Pull request merged**
